//
//  language_primary.h
//  TameParse
//
//  Created by Andrew Hunter on 10/09/2011.
//  Copyright 2011 _Andrew Hunter_. All rights reserved.
//

#include "test_fixture.h"

/// Tests for the 'primary' language generated by the bootstrapper
class test_language_primary : public test_fixture {
private:

public:
	test_language_primary() : test_fixture("language-primary") { }

	virtual void run_tests();
};
