<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comments</key>
	<dict>
		<key>patterns</key>
		<array>
			<dict>
				<key>begin</key>
				<string>/\*</string>
				<key>end</key>
				<string>\*/</string>
				<key>name</key>
				<string>comment.block.tameparse</string>
			</dict>
			<dict>
				<key>begin</key>
				<string>//</string>
				<key>end</key>
				<string>$\n?</string>
				<key>name</key>
				<string>comment.line.tameparse</string>
			</dict>
		</array>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>tp</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>name</key>
	<string>TameParse</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(language|import|lexer-symbols|lexer|ignore|weak|keywords|grammar|replace|parser|test|form|case|sensitive|insensitive)\b</string>
			<key>name</key>
			<string>keyword.control.tameparse</string>
		</dict>
		<dict>
			<key>match</key>
			<string>&lt;[^&gt;]*&gt;</string>
			<key>name</key>
			<string>entity.name.function.tameparse</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.tameparse</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.tameparse</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.tameparse</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.untitled</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.tameparse</string>
	<key>uuid</key>
	<string>22CF23EF-5707-47B2-B00F-76D40D48E0AA</string>
</dict>
</plist>
