#!/usr/bin/perl

##
## Converts the UnicodeData.txt file into a C database
##

# Iterate through stdin
$charRanges = { };

while ($_ = <>) {
	# Read out the character identifier and type
	if (/^([0-9A-Fa-f]*)\;[^;]*;([^;]*);/) {
		# Get the character number and type
		$charNum 	= hex($1);
		$charType	= $2;

		# Get the range array for this value
		$rangeArray = $charRanges->{$charType};

		$size = @$rangeArray;
		if ($size == 0) {
			# Just add a single range if the array is empty
			push(@$rangeArray, [ $charNum, $charNum ]);
		} else {
			# Get the last item
			$lastRange = $rangeArray->[-1];

			# Compare to the character
			if ($lastRange->[1] == $charNum - 1) {
				# Just update the range
				$lastRange->[1] = $charNum;
			} else {
				# Start a new range
				push(@$rangeArray, [ $charNum, $charNum ]);
			}
		}

		# Store in the hash
		$charRanges->{$charType} = $rangeArray;
	}
}

# Iterate through the arrays
print "/* Unicode character type table generated by unicode.pl */\n";

print "{";
$first = 1;
foreach my $key (keys %$charRanges) {
	if (!$first) {
		print ",";
	}

	print "\n    \"$key\", { ";

	$moreFirst = 1;
	$rangeArray = $charRanges->{$key};
	foreach my $range (@$rangeArray) {
		if (!$moreFirst) {
			print ", ";
		}

		$start = $range->[0];
		$end = $range->[1] + 1;
		print "{ $start, $end }";
		$moreFirst = 0;
	}
	print " }";

	$first = 0;
}
print "\n};\n";
