//
//  lexer_data.h
//  TameParse
//
//  Created by Andrew Hunter on 12/11/2011.
//  Copyright (c) 2011 __MyCompanyName__. All rights reserved.
//

#ifndef _COMPILER_DATA_LEXER_DATA_H
#define _COMPILER_DATA_LEXER_DATA_H

namespace compiler {
    ///
    /// \brief Data generated by the compiler to represent a lexer
    ///
    class lexer_data {
    private:
    };
}

#endif
